# Generated by Django 3.1.3 on 2020-11-16 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id_bag', models.AutoField(primary_key=True, serialize=False)),
                ('qr_code', models.CharField(max_length=50, unique=True, verbose_name='OR Code')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('date_discarded', models.DateTimeField(verbose_name='Date Discarded')),
                ('bag_type', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, verbose_name='Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bag',
                'verbose_name_plural': 'Bags',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id_branch', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id_store', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('category', models.CharField(choices=[('S', 'Supermarket'), ('P', 'Perfumery'), ('D', 'Department Store'), ('G', 'Gift Shop')], max_length=20, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id_purchase', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('eco_points', models.PositiveIntegerField(verbose_name='EcoPoints')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Purchase Total')),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='commerce.bag')),
                ('store_branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='commerce.branch')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='commerce.store'),
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('eco_points', models.PositiveIntegerField(verbose_name='EcoPoints')),
                ('store_branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='commerce.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchanges',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
