# Generated by Django 3.1.3 on 2020-11-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20201118_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='Longitude'),
        ),
    ]
