# Generated by Django 3.1.3 on 2020-11-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_auto_20201118_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='close_time',
            new_name='closeTime',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='open_time',
            new_name='openTime',
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
    ]
