# Generated by Django 3.1.3 on 2020-11-18 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_auto_20201118_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(default=1, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='store', to='commerce.store'),
        ),
    ]
