# Generated by Django 3.1.3 on 2020-11-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_auto_20201118_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Bag name'),
        ),
    ]
