# Generated by Django 3.1.3 on 2020-11-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201116_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ci',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='CI'),
        ),
    ]
