# Generated by Django 3.1.3 on 2020-11-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201116_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='Phone Number'),
        ),
    ]
